name: "Mirroring Repository"
description: "Mirror a repository to another repository on GitHub, GitLab, BitBucket, AWS CodeCommit, etc."
branding:
  icon: "archive"
  color: "blue"
inputs:
  ssh_private_key:
    description: "SSH private key for ssh connection to the target repository"
    required: false
  target_repo_url:
    description: "Target url"
    required: true
  host_key:
    description: "aws key"
    required: true
  ssh_config:
    description: "config file"
    required: true
  ssh_public_key:
    description: "SSH public key for ssh connection to the target repository"
    required: false
    default: "git"
  aws_region:
    description: "aws region"
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
